Repository prose-im/prose-pod-api, pull requests merged in 2025-04, with the labels that each got.

#200 Remove API discrepancies and add missing CRUD routes
  CHANGELOG.md
  docs/openapi/features/invitations.yaml
  docs/openapi/features/members.yaml
  docs/openapi/features/pod-config.yaml
  docs/openapi/features/roles.yaml
  docs/openapi/features/server-config.yaml
  docs/openapi/features/workspace.yaml
  docs/openapi/openapi.yaml
  docs/openapi/shared.yaml
  src/rest-api/src/features/init/init_workspace.rs
  src/rest-api/src/features/pod_config/dashboard_url.rs
  src/rest-api/src/features/pod_config/guards/pod_network_config.rs
  src/rest-api/src/features/pod_config/mod.rs
  src/rest-api/src/features/pod_config/pod_address.rs
  src/rest-api/src/features/pod_config/pod_config.rs
  src/rest-api/src/features/pod_config/util.rs
  src/rest-api/src/features/roles/set_member_role.rs
  src/rest-api/src/features/server_config/file_upload.rs
  src/rest-api/src/features/server_config/get_server_config.rs
  src/rest-api/src/features/server_config/message_archive.rs
  src/rest-api/src/features/server_config/mod.rs
  src/rest-api/src/features/server_config/network_encryption.rs
  src/rest-api/src/features/server_config/push_notifications.rs
  src/rest-api/src/features/server_config/routes.rs
  src/rest-api/src/features/server_config/server_federation.rs
  src/rest-api/src/features/server_config/util.rs
  src/rest-api/src/features/workspace_details/workspace_accent_color.rs
  src/rest-api/src/features/workspace_details/workspace_icon.rs
  src/rest-api/src/features/workspace_details/workspace_name.rs
  src/rest-api/tests/features/dns_setup.rs
  src/rest-api/tests/features/init.rs
  src/rest-api/tests/features/pod_config.rs
  src/rest-api/tests/features/roles.rs
  src/rest-api/tests/features/server_config.rs
  src/rest-api/tests/features/workspace_details.rs
  src/rest-api/tests/prelude/util.rs
  src/service/src/features/members/member_repository.rs
  src/service/src/features/members/member_service.rs
  src/service/src/features/pod_config/entities/pod_config.rs
  src/service/src/features/pod_config/models/pod_config.rs
  src/service/src/features/pod_config/pod_config_repository.rs
  src/service/src/features/workspace/workspace_service.rs
  src/service/src/features/xmpp/server_manager.rs
  src/service/src/models/sea_orm.rs
  src/service/src/util/sea_orm.rs
  tests/integration/step-ci/init.yaml
  tests/integration/step-ci/pod-config.yaml
  tests/integration/step-ci/workspace.yaml
Labels: documentation, enhancement, cleanup, breaking

#202 feat: Add Workspace XMPP account to everyone’s rosters
  src/rest-api/src/features/init/init_server_config.rs
  src/rest-api/src/features/startup_actions/add_workspace_to_team.rs
  src/rest-api/src/features/startup_actions/mod.rs
  src/service/src/features/init/init_service.rs
Labels: fix

#206 feat: Add expert Prosody routes
  docs/openapi/features/prosody.yaml
  docs/openapi/openapi.yaml
  src/rest-api/src/error/mod.rs
  src/rest-api/src/features/server_config/guards/mod.rs
  src/rest-api/src/features/server_config/guards/server_config.rs
  src/rest-api/src/features/server_config/mod.rs
  src/rest-api/src/features/server_config/prosody_routes.rs
  src/rest-api/src/guards/mod.rs
  src/service/src/features/prosody/mod.rs
  src/service/src/features/prosody/prosody_config_from_db.rs
  src/service/src/features/prosody/prosody_overrides.rs
  src/service/src/features/server_config/entities/server_config.rs
  src/service/src/features/server_config/migrations/m20250404_193000_add_prosody_overrides.rs
  src/service/src/features/server_config/migrations/mod.rs
  src/service/src/features/server_config/models/server_config.rs
  src/service/src/features/server_config/server_config_repository.rs
  src/service/src/features/xmpp/server_manager.rs
  src/service/src/migrations/mod.rs
  src/service/src/util/either.rs
Labels: documentation, enhancement

#207 feat: Add `PUT|GET|DELETE /v1/server/config/prosody-overrides-raw`
  README.md
  docs/openapi/features/prosody.yaml
  docs/openapi/openapi.yaml
  src/prosody-config/src/prosody_config/mod.rs
  src/prosody-config/src/prosody_config_file/print.rs
  src/rest-api/src/features/server_config/guards/lua.rs
  src/rest-api/src/features/server_config/guards/mod.rs
  src/rest-api/src/features/server_config/mod.rs
  src/rest-api/src/features/server_config/prosody_routes.rs
  src/service/src/features/prosody/prosody_config.rs
  src/service/src/features/server_config/entities/server_config.rs
  src/service/src/features/server_config/migrations/m20250407_014800_add_prosody_overrides_raw.rs
  src/service/src/features/server_config/migrations/mod.rs
  src/service/src/features/server_config/models/server_config.rs
  src/service/src/features/xmpp/live_server_ctl.rs
  src/service/src/features/xmpp/server_manager.rs
  src/service/src/migrations/mod.rs
  src/service/tests/prosody/mod.rs
Labels: documentation, enhancement

#209 feat(startup): Add `migrate_workspace_vcard` startup action
  src/rest-api/src/features/startup_actions/migrate_workspace_vcard.rs
  src/rest-api/src/features/startup_actions/mod.rs
  src/service/src/features/app_config/mod.rs
  src/service/src/features/workspace/models/workspace.rs
  src/service/src/features/workspace/workspace_service.rs
  tests/integration/Prose-tokens-expired.toml
  tests/integration/step-ci/auth-expired.yaml
Labels: fix

#213 fix: Refresh service accounts OAuth tokens before they expire
  src/rest-api/src/features/startup_actions/mod.rs
  src/rest-api/src/features/startup_actions/start_cron_tasks.rs
  src/rest-api/src/util/lifecycle_manager.rs
  src/rest-api/tests/prelude/mocks/mock_secrets_store.rs
  src/service/src/features/cron/mod.rs
  src/service/src/features/cron/refresh_service_accounts_tokens.rs
  src/service/src/features/mod.rs
  src/service/src/features/prosody/prosody_rest.rs
  src/service/src/features/secrets/live_secrets_store.rs
  src/service/src/features/secrets/secrets_store.rs
  src/service/src/features/xmpp/server_manager.rs
Labels: fix

#215 fix: Fix API hangs when running network checks after 5 minutes
  src/service/src/features/network_checks/live_network_checker.rs
Labels: fix

#217 feat: Improve emails
  src/rest-api/tests/prelude/notifier.rs
  src/service/src/features/invitations/models/workspace_invitation_notification.rs
  src/service/src/features/notifications/dependencies/notifier/email.rs
Labels: enhancement, fix

#218 Create release after tests pass #93
  .github/workflows/release.yaml
Labels: enhancement, ci

#221 feat: Implement the 100 members limit
  .github/workflows/test.yaml
  Taskfile.dist.yaml
  features/members/member-limit.feature
  src/rest-api/Cargo.toml
  src/rest-api/src/features/invitations/invitation_actions.rs
  src/rest-api/src/features/members/mod.rs
  src/rest-api/tests/features/init.rs
  src/rest-api/tests/features/invitations.rs
  src/rest-api/tests/features/members.rs
  src/rest-api/tests/prelude/steps.rs
  src/rest-api/tests/prelude/test_world.rs
  src/service/Cargo.toml
  src/service/src/features/members/unauthenticated_member_service.rs
Labels: enhancement

#225 Allow (de)serialization of Prosody config parts
  Cargo.lock
  src/prosody-config/Cargo.toml
  src/prosody-config/src/model/secrets.rs
  src/prosody-config/src/model/xmpp.rs
  src/prosody-config/src/prosody_config/conversion.rs
  src/prosody-config/src/prosody_config/mod.rs
  src/prosody-config/src/prosody_config_file/mod.rs
  src/prosody-config/tests/serde.rs
  src/service/src/features/prosody/prosody_bootstrap_config.rs
  src/service/src/features/prosody/prosody_config.rs
Labels: enhancement

#228 feat(members): Allow searching for members using the `q` query parameter
  Cargo.lock
  Cargo.toml
  src/rest-api/src/features/members/get_members.rs
  src/rest-api/src/features/members/guards/member_service.rs
  src/rest-api/src/forms/mod.rs
  src/rest-api/src/forms/opt_query.rs
  src/rest-api/src/forms/search_query.rs
  src/service/Cargo.toml
  src/service/src/features/members/member_repository.rs
  src/service/src/features/members/member_service.rs
  src/service/src/util/concurrent_task_runner.rs
  src/service/src/util/mod.rs
  src/service/src/util/unaccent.rs
Labels: enhancement

#229 Optimize members enriching
  src/rest-api/src/features/members/enrich_members.rs
  src/rest-api/src/features/members/get_member.rs
  src/rest-api/src/features/members/get_members.rs
  src/service/src/features/members/member_repository.rs
  src/service/src/features/members/member_service.rs
  src/service/src/util/cache.rs
  src/service/src/util/mod.rs
Labels: enhancement, cleanup, performance

#232 feat(workspace-details)!: Accept content types when setting and getting the Workspace icon
  docs/openapi/features/members.yaml
  docs/openapi/features/workspace.yaml
  docs/openapi/shared.yaml
  features/workspace-details/workspace-icon.feature
  src/rest-api/src/error/errors.rs
  src/rest-api/src/features/members/mod.rs
  src/rest-api/src/features/network_checks/mod.rs
  src/rest-api/src/features/profile/set_member_avatar.rs
  src/rest-api/src/features/workspace_details/mod.rs
  src/rest-api/src/features/workspace_details/workspace_icon.rs
  src/rest-api/src/util/content_type_or.rs
  src/rest-api/tests/features/members.rs
  src/rest-api/tests/features/workspace_details.rs
  src/rest-api/tests/prelude/mocks/mock_xmpp_service.rs
  src/rest-api/tests/prelude/util.rs
  src/service/src/features/members/member_service.rs
  src/service/src/features/workspace/models/workspace.rs
  src/service/src/features/workspace/workspace_service.rs
  src/service/src/features/xmpp/live_xmpp_service/live_xmpp_service.rs
  src/service/src/features/xmpp/xmpp_service.rs
  tests/integration/step-ci/workspace.yaml
Labels: documentation, enhancement, breaking
